make OBJ/PROGRAMS/crc32/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/cubic/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/dhrystone/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/edn/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/fibonacci/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/huffbench/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/matmult-int/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/md5sum/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/minver/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/mont64/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/nbody/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/nettle-aes/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/nettle-sha256/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/nsichneu/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/picojpeg/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/primecount/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/qrduino/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/sglib-combined/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/slre/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/st/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/statemate/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/tarfind/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/ud/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/verifypin_0/SIM/LOG/program_encrypted_verif.log
make OBJ/PROGRAMS/wikisort/SIM/LOG/program_encrypted_verif.log
