#!/bin/python3
"""
riscv-launcher.py

This script analyzes campaign 'try_freq' by displaying graph of WNS, LUT and FF utilization.
"""

import argparse
import os
import re
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('tableau-colorblind10')



###### Arguments ######
parser = argparse.ArgumentParser(description="Analyze report generated by vivado_try_freq.tcl")
parser.add_argument(
    "try_freq_p",
    help="Path to try_freq folder",
    type=str, nargs='?', const="", default=""
)
parser.add_argument(
    "-t",
    "--top",
    help="Plot top module utilization only",
    action="store_true"
)
parser.add_argument(
    "-a",
    "--all",
    help="Bar all module utilization",
    action="store_true"
)
parser.add_argument(
    "-s",
    "--save_fig",
    help="Save figures",
    action="store_true"
)
parser.add_argument(
    "-d",
    "--display_fig",
    help="Display figure",
    action="store_true"
)
parser.add_argument(
    "-p",
    "--parameters",
    help="Display additionnal parameters in graph.",
    action="store_true"
)

args = parser.parse_args()

plot_dir = re.sub('[^/]*/try_freq.*','',args.try_freq_p)
project_name = re.sub('/','',re.sub('.*/[^/]','',re.sub('/try_freq','',args.try_freq_p)))
name = re.sub("/", "", re.sub("\.", "", re.sub(".*VIVADO_OBJ_DIR", "", plot_dir)))


def read_parameters():
    with open(f"{args.try_freq_p}/try_freq.log", 'r') as file:
        try_freq_log_s_l  = file.read().split('\n')

    i = 0
    synth_line = -1
    impl_line = -1
    while i < len(try_freq_log_s_l):
        if "Synthesis strategy:" in try_freq_log_s_l[i]:
            synth_line = i
        if "Implementation strategy: " in try_freq_log_s_l[i]:
            impl_line = i
        i += 1
    synth_strat = re.sub('[^:]*:\s*','',try_freq_log_s_l[synth_line])
    impl_strat = re.sub('[^:]*:\s*','',try_freq_log_s_l[impl_line])

    return(synth_strat, impl_strat)


if args.parameters:
    synth_strat, impl_strat = read_parameters()


def get_wns(timing_rpt_p):
    with open(timing_rpt_p , 'r') as file:
        timing_s_l = file.read().split('\n')
    i = 0
    while "| Design Timing Summary" not in timing_s_l[i]:
        i += 1
    i += 6
    return(float(list(filter(('').__ne__, timing_s_l[i].split(' ')))[0]))


def get_lut_ff(utilization_rpt_p):
    with open(utilization_rpt_p, 'r') as file:
        utilization_s_l = file.read().split('\n')
    i = 0
    while "Instance" not in utilization_s_l[i]:
        i += 1
    i+=2 # Two lines above data
    top_utilization_l = [x.replace(" ","") for x in utilization_s_l[i].split("|")]
    return (int(top_utilization_l[4]), int(top_utilization_l[7]))

def count_depth(instance_s):
    i = 0
    while instance_s[i] == " ":
        i +=1
    return ((i-1)//2)

def get_hierarchical_utilization(utilization_rpt_p):
    with open(utilization_rpt_p, 'r') as file:
        utilization_s_l = file.read().split('\n')
    i = 0
    while "Instance" not in utilization_s_l[i]:
        i += 1
    i+=2 # Two lines above data

    hierarchical_utilization_d = {}
    last_parents = [""]*10

    while "+-----------------------------" not in utilization_s_l[i]:
        utilization_l = utilization_s_l[i].split("|")
        depth = count_depth(utilization_l[1])
        utilization_l = [x.replace(" ","") for x in utilization_l]
        utilization_l = list(filter(('').__ne__, utilization_l))
        if utilization_l[0] in hierarchical_utilization_d.keys():
            instance_indexed = 2
            while f"{utilization_l[0]}_{instance_indexed}" in hierarchical_utilization_d.keys():
                instance_indexed += 1
            utilization_l[0] += f"_{instance_indexed}"

        hierarchical_utilization_d[utilization_l[0]] = {}
        hierarchical_utilization_d[utilization_l[0]]['depth'] = depth
        hierarchical_utilization_d[utilization_l[0]]['LUTs'] = int(utilization_l[3])
        hierarchical_utilization_d[utilization_l[0]]['FFs'] = int(utilization_l[6])
        hierarchical_utilization_d[utilization_l[0]]['childs'] = []
        hierarchical_utilization_d[utilization_l[0]]['parent'] = last_parents[depth-1]
        if hierarchical_utilization_d[utilization_l[0]]['parent'] != "":
            hierarchical_utilization_d[last_parents[depth-1]]['childs'].append(utilization_l[0])
        last_parents[depth] = utilization_l[0]

        i += 1
    return (hierarchical_utilization_d)


def plot_top(impl_d, clk_factor):
    fcore_plt_l = list(impl_d.keys())
    fcore_plt_l.sort()

    txt_log = ""
    lut_plt_l, ff_plt_l, wns_plt_l = [], [], []
    for fcore in fcore_plt_l:
        lut_plt_l.append(impl_d[fcore]["lut"])
        ff_plt_l.append(impl_d[fcore]["ff"])
        wns_plt_l.append(impl_d[fcore]["wns"])
        txt_log += f"{round(fcore):<2}, {impl_d[fcore]['lut']:>5}, {impl_d[fcore]['ff']:>5}, {impl_d[fcore]['wns']:>000.3f}\n"


    # Plot setup
    fig, (ax1 , ax2)= plt.subplots(2, 1, figsize=(16*1.2, 9*1.2))
    #fig.figure(figsize=(10, 8))

    #plt.axhline(y=0, color="black", linewidth=0.25)
    extra_title = f" Synth={synth_strat}/Impl={impl_strat}" if args.parameters else ""
    ax1.set_title(f'WNS (CLK FACTOR={clk_factor}/HW PERM={6/clk_factor}){extra_title}')
    ax1.set_xlabel('Core frequency (MHz)')
    ax1.set_ylabel('WNS (ns)', color='C0')
    ax1.plot(fcore_plt_l, wns_plt_l, "-", linewidth=2, label="wns", color='C0')
    ax1.plot((fcore_plt_l[0], fcore_plt_l[-1]), (0, 0), "r-", linewidth=1)
    ax1.tick_params(axis='y', labelcolor='C0')
    ax1.legend()

    #ax2 = ax1.twinx()
    ax2.set_title(f'Utilization (CLK FACTOR={clk_factor}/HW PERM={6/clk_factor}){extra_title}')
    ax2.set_xlabel('Core frequency (MHz)')
#    ax2.set_ylabel('number', color='C1')
    ax2.plot(fcore_plt_l, lut_plt_l, "--", linewidth=2, label="lut", color='C1')
    ax2.plot(fcore_plt_l, ff_plt_l, "--", linewidth=2, label="ff", color='C2')
    ymin, ymax = 0, 10000
    ax2.set_ylim([ymin, ymax])
    ax2.tick_params(axis='y', labelcolor='C1')
    ax2.legend()

    plt.subplots_adjust(left=0.05, right=0.96, top=0.95, bottom=0.07)
    if args.save_fig:
        if not os.path.exists(f"{args.try_freq_p}/plot"):
            os.mkdir(f"{args.try_freq_p}/plot")
        extra_name = f"__Synth-{synth_strat.replace(' ','-')}_Impl-{impl_strat.replace(' ','-')}" if args.parameters else ""
        plt.savefig(f"{args.try_freq_p}/plot/{name}_plot__WNS__FF-top__LUT-top__CLK-FACTOR-{clk_factor}{extra_name}.pdf")
        with open(f"{args.try_freq_p}/plot/{name}_plot__WNS__FF-top__LUT-top__CLK-FACTOR-{clk_factor}{extra_name}.log", "w") as file:
            file.write(txt_log) 

def bar_all_instances(impl_d, clk_factor):
    fcore_plt_l = list(impl_d.keys())
    fcore_plt_l.sort()

    instances_lut_d = {}
    instances_ff_d = {}
    for instance in impl_d[fcore_plt_l[0]]['utilization']:
        if impl_d[fcore_plt_l[0]]['utilization'][instance]['childs'] == [] or instance[0] == "(":
            instances_lut_d[instance] = []
            instances_ff_d[instance] = []

    fcore_wns_neg_l = []
    for fcore in fcore_plt_l:
        if impl_d[fcore]['wns'] < 0:
            fcore_wns_neg_l.append(fcore)

        for instance in impl_d[fcore]['utilization']:
            if impl_d[fcore_plt_l[0]]['utilization'][instance]['childs'] == [] or instance[0] == "(":
                instances_lut_d[instance].append(np.array(impl_d[fcore]['utilization'][instance]['LUTs']))
                instances_ff_d[instance].append(np.array(impl_d[fcore]['utilization'][instance]['FFs']))

    width = 0.95

    fig1, ax1 = plt.subplots(figsize=(16*1.2, 9*1.2))
    bottom = np.zeros(len(fcore_plt_l))
    instance_lut_d_items_reversed = list(instances_lut_d.items())
    instance_lut_d_items_reversed.reverse()

    for instance, lut in instance_lut_d_items_reversed:
        p = ax1.bar(fcore_plt_l, lut , width, label=f"{'    '*impl_d[fcore_plt_l[0]]['utilization'][instance]['depth']}{instance}", bottom=bottom)
        bottom += lut
        #ax1.bar_label(p, label_type='center')
    ax1.plot(fcore_wns_neg_l, [75]*(len(fcore_wns_neg_l)), "X", ms=16, color='red')
    extra_title = f" Synth={synth_strat}/Impl={impl_strat}" if args.parameters else ""
    ax1.set_title(f'LUTs utilization (CLK FACTOR={clk_factor}/HW PERM={6/clk_factor}){extra_title}')
    ax1.set_xlabel('Core frequency (MHz)')

    # reverse the order
    handles, labels = ax1.get_legend_handles_labels()
    ax1.legend(handles[::-1], labels[::-1])
    #fig1.tight_layout(pad=0.4, w_pad=0.5, h_pad=1.0)
    plt.subplots_adjust(left=0.05, right=0.96, top=0.95, bottom=0.07)
    if args.save_fig:
        if not os.path.exists(f"{args.try_freq_p}/plot"):
            os.mkdir(f"{args.try_freq_p}/plot")
        extra_name = f"__Synth-{synth_strat.replace(' ','-')}_Impl-{impl_strat.replace(' ','-')}" if args.parameters else ""
        plt.savefig(f"{args.try_freq_p}/plot/{name}_bar__LUT-all__CLK-FACTOR-{clk_factor}{extra_name}.pdf")


    fig2, ax2 = plt.subplots(figsize=(16*1.2, 9*1.2))
    bottom = np.zeros(len(fcore_plt_l))
    instance_ff_d_items_reversed = list(instances_ff_d.items())
    instance_ff_d_items_reversed.reverse()

    for instance, ff in instance_ff_d_items_reversed:
        p = ax2.bar(fcore_plt_l, ff , width, label=f"{'    '*impl_d[fcore_plt_l[0]]['utilization'][instance]['depth']}{instance}", bottom=bottom)
        bottom += ff
        #ax2.bar_label(p, label_type='center')
    ax2.plot(fcore_wns_neg_l, [75]*(len(fcore_wns_neg_l)), "X", ms=16, color='red')
    ax2.set_title(f'FFs utilization (CLK FACTOR={clk_factor}/HW PERM={6/clk_factor}){extra_title}')
    ax2.set_xlabel('Core frequency (MHz)')

    # reverse the order
    handles, labels = ax2.get_legend_handles_labels()
    ax2.legend(handles[::-1], labels[::-1])
    #fig2.tight_layout(pad=0.4, w_pad=0.5, h_pad=1.0)
    plt.subplots_adjust(left=0.05, right=0.96, top=0.95, bottom=0.07)
    if args.save_fig:
        if not os.path.exists(f"{args.try_freq_p}/plot"):
            os.mkdir(f"{args.try_freq_p}/plot")
        extra_name = f"__Synth-{synth_strat.replace(' ','-')}_Impl-{impl_strat.replace(' ','-')}" if args.parameters else ""
        plt.savefig(f"{args.try_freq_p}/plot/{name}_bar__FF-all__CLK-FACTOR-{clk_factor}{extra_name}.pdf")


def display_graph(impl_d, clk_factor):
    plt.rc('font', family='serif')
    if args.top:
        plot_top(impl_d, clk_factor)
    if args.all:
        bar_all_instances(impl_d, clk_factor)
    if args.display_fig:
        plt.show()

def read_reports():
    # List all frequencies in 'try_freq' folder
    freq_names = [f for f in os.listdir(args.try_freq_p) if os.path.isdir(os.path.join(args.try_freq_p, f))]
    if "plot" in freq_names:
        freq_names.remove("plot")

    # Build dictionnary (key: core frequency, val: dictionnary with the prefix path to reports)
    impl_d = {}
    clk_factor = -1
    for f_s in freq_names:
        f_l = f_s.split("_")
        fcore, fascon = float(f_l[1].replace('-','.')), float(f_l[2].replace('-','.'))
        if clk_factor == -1:
            clk_factor = round(fascon / fcore)
        elif clk_factor != round(fascon / fcore):
            raise ValueError('Different clk_factor configuration used.')
        impl_d[fcore] = {}
        impl_d[fcore]['prefix'] = f"{args.try_freq_p}/{f_s}/{name}_{f_s}"

    # Open reports
    for fcore in impl_d:
        timing_rpt_p = f"{impl_d[fcore]['prefix']}_timing.rpt"
        utilization_rpt_p = f"{impl_d[fcore]['prefix']}_report_utilization_hierarchical.rpt"

        impl_d[fcore]['lut'], impl_d[fcore]['ff'] = get_lut_ff(utilization_rpt_p)
        impl_d[fcore]['wns'] = get_wns(timing_rpt_p)
        impl_d[fcore]['utilization'] = get_hierarchical_utilization(utilization_rpt_p)

    display_graph(impl_d, clk_factor)





if __name__ == "__main__":
    read_reports()
